// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4qbN9NIt2G9wvbnOEYt312KksM2HVM4',
    appId: '1:573474302271:web:a7cf3a160d378759338b8a',
    messagingSenderId: '573474302271',
    projectId: 'ecommerceapp-6248e',
    authDomain: 'ecommerceapp-6248e.firebaseapp.com',
    storageBucket: 'ecommerceapp-6248e.appspot.com',
    measurementId: 'G-W7X6DE2B7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeIyz_oS_hB4UXCol4V6b8zTGbyd90DII',
    appId: '1:573474302271:android:886c4229100bf3b7338b8a',
    messagingSenderId: '573474302271',
    projectId: 'ecommerceapp-6248e',
    storageBucket: 'ecommerceapp-6248e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDcrH_hQal_apoHDfV3WbyHGmmtr0sMI',
    appId: '1:573474302271:ios:3f0f3d503ceeaf7c338b8a',
    messagingSenderId: '573474302271',
    projectId: 'ecommerceapp-6248e',
    storageBucket: 'ecommerceapp-6248e.appspot.com',
    androidClientId: '573474302271-e14f3uf28liakqpk9ip98p0gbl7h1h0u.apps.googleusercontent.com',
    iosClientId: '573474302271-ta9krcnqospv4tfp9vbvsehgmcfmhd3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApDcrH_hQal_apoHDfV3WbyHGmmtr0sMI',
    appId: '1:573474302271:ios:d20ea8d8f9e37d81338b8a',
    messagingSenderId: '573474302271',
    projectId: 'ecommerceapp-6248e',
    storageBucket: 'ecommerceapp-6248e.appspot.com',
    androidClientId: '573474302271-e14f3uf28liakqpk9ip98p0gbl7h1h0u.apps.googleusercontent.com',
    iosClientId: '573474302271-aedjdfg96q9k58ho6idedecq88fl2b86.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel.RunnerTests',
  );
}
